### ISSUE TITLE
Still saying every username is available

### ISSUE THREAD

**Issue by swiftscripts0** [suegdu/Discord-Username-Checker#7]
After the previous issue that I opened and you said you fixed it still says every username in my usernames.txt file is available when they are not.

I'm not sure if it's because I am on macOS or not.

![Screen Shot 2023-06-21 at 6 40 41 pm](https://github.com/suegdu/DSV/assets/86579464/1acce98b-b8da-4a17-b2a7-f6165c7a9f6c)

**Comment by suegdu** [comment]
It appears like that the token of the account you have entered did not receive the name update (**It shows a discriminator**). As i mentioned earlier in the notes if your account did not receive a username change then it will glitch out saying they are all available.

**Comment by suegdu** [comment]
Your account must receive the username update where it won't show a discriminator and it will be displayed **as #0** in the ***Connected as*** section.

**Comment by suegdu** [comment]
May i ask what's the **creation date** of your Discord account?

**Comment by zekepetherick** [comment]
The token I was using does have the update I just haven't changed the username to remove the discriminator, is that  problem?

![Screen Shot 2023-06-21 at 7 18 21 pm](https://github.com/suegdu/DSV/assets/86579464/ad4a004f-9823-4bd5-9da0-913829770628)

**Comment by zekepetherick** [comment]
Do you have a discord that I can add or server i can join so I can reply faster?

**Comment by suegdu** [comment]
> The token I was using does have the update I just haven't changed the username to remove the discriminator, is that problem?
> 
> ![Screen Shot 2023-06-21 at 7 18 21 pm](https://user-images.githubusercontent.com/86579464/247507654-ad4a004f-9823-4bd5-9da0-913829770628.png)

Yes it is a problem, you must apply to the update and remove the discriminator, it's discord that operates like that not my checker btw

**Comment by suegdu** [comment]
> Do you have a discord that I can add or server i can join so I can reply faster?

Talking over Discord with subjects like this results in a ban 
*It already happened to one of my accounts*

**Comment by zekepetherick** [comment]
> > The token I was using does have the update I just haven't changed the username to remove the discriminator, is that problem?
> > ![Screen Shot 2023-06-21 at 7 18 21 pm](https://user-images.githubusercontent.com/86579464/247507654-ad4a004f-9823-4bd5-9da0-913829770628.png)
> 
> Yes it is a problem, you must apply to the update and remove the discriminator, it's discord that operates like that not my checker btw

I have changed the name of my token to one without a discriminator and it is fully working!

**Comment by zekepetherick** [comment]
You should create a guilded server to chat in about projects like these.

**Comment by suegdu** [comment]
> > > The token I was using does have the update I just haven't changed the username to remove the discriminator, is that problem?
> > > ![Screen Shot 2023-06-21 at 7 18 21 pm](https://user-images.githubusercontent.com/86579464/247507654-ad4a004f-9823-4bd5-9da0-913829770628.png)
> > 
> > 
> > Yes it is a problem, you must apply to the update and remove the discriminator, it's discord that operates like that not my checker btw
> 
> I have changed the name of my token to one without a discriminator and it is fully working!

great to hear that

**Comment by zekepetherick** [comment]
> > You should create a guilded server to chat in about projects like these.
> 
> I really wish to do so but unfortunately I wouldn't like to risk more accounts since most of them got banned because of doing this, I had a guild discussing about topics like this and my account was immediately banned.

Not a discord guild. The platform guilded.

**Comment by suegdu** [comment]
Oh my bad I'll look into it if it's possible

**Comment by zekepetherick** [comment]
No worries, I don't know much about that platform myself but I am willing to help you set one up.

**Comment by suegdu** [comment]
Hope the checker works great with you and be happy to drop a star because it helps the project

**Comment by zekepetherick** [comment]
Will do, have a nice day!

**Comment by suegdu** [comment]
You too, thanks for you time
